/**
 * Dummy customer data for the ERP system
 * 
 * This file contains sample data for customers to populate
 * the customer management section of the application.
 */

// Create dummy customers
const customers = [
  {
    id: 'cust_001',
    code: 'CUST001',
    name: 'Green Leaf Dispensary',
    contact: 'Sarah Johnson',
    email: 'sarah@greenleafdispensary.com',
    phone: '503-555-1234',
    address: {
      street: '123 Main Street',
      city: 'Portland',
      state: 'OR',
      zip: '97205',
      country: 'USA',
    },
    status: 'active',
    creditLimit: 10000.00,
    paymentTerms: 'Net 30',
    notes: 'Premium client, always pays on time',
    customFields: {
      licenseNumber: 'OR-DIS-12345',
      preferredDeliveryDay: 'Tuesday',
      salesTaxExempt: true
    },
    createdAt: new Date('2023-11-15'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: 'cust_002',
    code: 'CUST002',
    name: 'Herbal Wellness Center',
    contact: 'Michael Chen',
    email: 'michael@herbalwellness.com',
    phone: '503-555-2345',
    address: {
      street: '456 Oak Avenue',
      city: 'Eugene',
      state: 'OR',
      zip: '97401',
      country: 'USA',
    },
    status: 'active',
    creditLimit: 8000.00,
    paymentTerms: 'Net 15',
    notes: 'Prefers delivery in the morning',
    customFields: {
      licenseNumber: 'OR-DIS-23456',
      preferredDeliveryDay: 'Thursday',
      salesTaxExempt: true
    },
    createdAt: new Date('2023-11-20'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'cust_003',
    code: 'CUST003',
    name: 'Pacific Northwest Herbals',
    contact: 'Jessica Martinez',
    email: 'jessica@pnwherbals.com',
    phone: '503-555-3456',
    address: {
      street: '789 Pine Street',
      city: 'Salem',
      state: 'OR',
      zip: '97301',
      country: 'USA',
    },
    status: 'active',
    creditLimit: 12000.00,
    paymentTerms: 'Net 30',
    notes: 'Large volume buyer, interested in bulk discounts',
    customFields: {
      licenseNumber: 'OR-DIS-34567',
      preferredDeliveryDay: 'Monday',
      salesTaxExempt: true
    },
    createdAt: new Date('2023-12-01'),
    updatedAt: new Date('2024-02-20'),
  },
  {
    id: 'cust_004',
    code: 'CUST004',
    name: 'Mountain High Dispensary',
    contact: 'David Wilson',
    email: 'david@mountainhigh.com',
    phone: '541-555-4567',
    address: {
      street: '101 Summit Road',
      city: 'Bend',
      state: 'OR',
      zip: '97701',
      country: 'USA',
    },
    status: 'active',
    creditLimit: 7500.00,
    paymentTerms: 'Net 15',
    notes: 'Specializes in premium products',
    customFields: {
      licenseNumber: 'OR-DIS-45678',
      preferredDeliveryDay: 'Wednesday',
      salesTaxExempt: true
    },
    createdAt: new Date('2023-12-10'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: 'cust_005',
    code: 'CUST005',
    name: 'Coastal Cannabis Co.',
    contact: 'Emily Brown',
    email: 'emily@coastalcannabis.com',
    phone: '541-555-5678',
    address: {
      street: '202 Beach Drive',
      city: 'Newport',
      state: 'OR',
      zip: '97365',
      country: 'USA',
    },
    status: 'active',
    creditLimit: 9000.00,
    paymentTerms: 'Net 30',
    notes: 'Seasonal business, higher volume in summer',
    customFields: {
      licenseNumber: 'OR-DIS-56789',
      preferredDeliveryDay: 'Friday',
      salesTaxExempt: true
    },
    createdAt: new Date('2023-12-15'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'cust_006',
    code: 'CUST006',
    name: 'Urban Leaf Collective',
    contact: 'Robert Taylor',
    email: 'robert@urbanleaf.com',
    phone: '503-555-6789',
    address: {
      street: '303 Downtown Blvd',
      city: 'Portland',
      state: 'OR',
      zip: '97209',
      country: 'USA',
    },
    status: 'active',
    creditLimit: 15000.00,
    paymentTerms: 'Net 30',
    notes: 'High-end retail location, focuses on premium products',
    customFields: {
      licenseNumber: 'OR-DIS-67890',
      preferredDeliveryDay: 'Tuesday',
      salesTaxExempt: true
    },
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: 'cust_007',
    code: 'CUST007',
    name: 'Valley View Cannabis',
    contact: 'Amanda Garcia',
    email: 'amanda@valleyview.com',
    phone: '541-555-7890',
    address: {
      street: '404 Valley Road',
      city: 'Medford',
      state: 'OR',
      zip: '97501',
      country: 'USA',
    },
    status: 'active',
    creditLimit: 6000.00,
    paymentTerms: 'Net 15',
    notes: 'New client, growing steadily',
    customFields: {
      licenseNumber: 'OR-DIS-78901',
      preferredDeliveryDay: 'Thursday',
      salesTaxExempt: true
    },
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: 'cust_008',
    code: 'CUST008',
    name: 'Evergreen Apothecary',
    contact: 'Daniel Lee',
    email: 'daniel@evergreenapothecary.com',
    phone: '503-555-8901',
    address: {
      street: '505 Forest Avenue',
      city: 'Portland',
      state: 'OR',
      zip: '97221',
      country: 'USA',
    },
    status: 'active',
    creditLimit: 11000.00,
    paymentTerms: 'Net 30',
    notes: 'Interested in expanding product range',
    customFields: {
      licenseNumber: 'OR-DIS-89012',
      preferredDeliveryDay: 'Monday',
      salesTaxExempt: true
    },
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-03-05'),
  },
  {
    id: 'cust_009',
    code: 'CUST009',
    name: 'Healing Roots Dispensary',
    contact: 'Sophia Patel',
    email: 'sophia@healingroots.com',
    phone: '541-555-9012',
    address: {
      street: '606 Wellness Way',
      city: 'Ashland',
      state: 'OR',
      zip: '97520',
      country: 'USA',
    },
    status: 'active',
    creditLimit: 8500.00,
    paymentTerms: 'Net 30',
    notes: 'Focuses on medicinal products',
    customFields: {
      licenseNumber: 'OR-DIS-90123',
      preferredDeliveryDay: 'Wednesday',
      salesTaxExempt: true
    },
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-02-25'),
  },
  {
    id: 'cust_010',
    code: 'CUST010',
    name: 'Cascade Cannabis Supply',
    contact: 'Thomas Rodriguez',
    email: 'thomas@cascadesupply.com',
    phone: '503-555-0123',
    address: {
      street: '707 Mountain View Road',
      city: 'Hood River',
      state: 'OR',
      zip: '97031',
      country: 'USA',
    },
    status: 'active',
    creditLimit: 20000.00,
    paymentTerms: 'Net 45',
    notes: 'Wholesale distributor, large volume orders',
    customFields: {
      licenseNumber: 'OR-WHOL-01234',
      preferredDeliveryDay: 'Friday',
      salesTaxExempt: true
    },
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: 'cust_011',
    code: 'CUST011',
    name: 'River City Hemp Co.',
    contact: 'Olivia Nelson',
    email: 'olivia@rivercityhemp.com',
    phone: '541-555-1234',
    address: {
      street: '808 Riverside Drive',
      city: 'Grants Pass',
      state: 'OR',
      zip: '97526',
      country: 'USA',
    },
    status: 'active',
    creditLimit: 7000.00,
    paymentTerms: 'Net 15',
    notes: 'Specializes in CBD products',
    customFields: {
      licenseNumber: 'OR-DIS-12345',
      preferredDeliveryDay: 'Tuesday',
      salesTaxExempt: true
    },
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'cust_012',
    code: 'CUST012',
    name: 'Emerald City Greens',
    contact: 'William Clark',
    email: 'william@emeraldcitygreens.com',
    phone: '503-555-2345',
    address: {
      street: '909 Emerald Street',
      city: 'Portland',
      state: 'OR',
      zip: '97211',
      country: 'USA',
    },
    status: 'inactive',
    creditLimit: 9500.00,
    paymentTerms: 'Net 30',
    notes: 'Account temporarily suspended due to license renewal',
    customFields: {
      licenseNumber: 'OR-DIS-23456',
      preferredDeliveryDay: 'Thursday',
      salesTaxExempt: true
    },
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: 'cust_013',
    code: 'CUST013',
    name: 'High Desert Herbals',
    contact: 'Natalie Kim',
    email: 'natalie@highdesertherbals.com',
    phone: '541-555-3456',
    address: {
      street: '1010 Desert Road',
      city: 'Redmond',
      state: 'OR',
      zip: '97756',
      country: 'USA',
    },
    status: 'active',
    creditLimit: 8000.00,
    paymentTerms: 'Net 30',
    notes: 'Interested in exclusive strains',
    customFields: {
      licenseNumber: 'OR-DIS-34567',
      preferredDeliveryDay: 'Monday',
      salesTaxExempt: true
    },
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-03-20'),
  },
  {
    id: 'cust_014',
    code: 'CUST014',
    name: 'Willamette Valley Cannabis',
    contact: 'Christopher Adams',
    email: 'chris@wvcannabis.com',
    phone: '503-555-4567',
    address: {
      street: '1111 Valley View Lane',
      city: 'Corvallis',
      state: 'OR',
      zip: '97330',
      country: 'USA',
    },
    status: 'pending',
    creditLimit: 5000.00,
    paymentTerms: 'Prepaid',
    notes: 'New account, pending final license verification',
    customFields: {
      licenseNumber: 'OR-DIS-45678-PENDING',
      preferredDeliveryDay: 'Wednesday',
      salesTaxExempt: false
    },
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: 'cust_015',
    code: 'CUST015',
    name: 'Pacific Crest Cannabis',
    contact: 'Jennifer White',
    email: 'jennifer@pacificcrest.com',
    phone: '541-555-5678',
    address: {
      street: '1212 Mountain Pass Road',
      city: 'Klamath Falls',
      state: 'OR',
      zip: '97601',
      country: 'USA',
    },
    status: 'active',
    creditLimit: 7500.00,
    paymentTerms: 'Net 15',
    notes: 'Prefers organic products',
    customFields: {
      licenseNumber: 'OR-DIS-56789',
      preferredDeliveryDay: 'Friday',
      salesTaxExempt: true
    },
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-03-25'),
  },
  {
    id: 'cust_016',
    code: 'CUST016',
    name: 'Rose City Remedies',
    contact: 'Andrew Scott',
    email: 'andrew@rosecityremedies.com',
    phone: '503-555-6789',
    address: {
      street: '1313 Rose Avenue',
      city: 'Portland',
      state: 'OR',
      zip: '97232',
      country: 'USA',
    },
    status: 'active',
    creditLimit: 10000.00,
    paymentTerms: 'Net 30',
    notes: 'Expanding to second location soon',
    customFields: {
      licenseNumber: 'OR-DIS-67890',
      preferredDeliveryDay: 'Tuesday',
      salesTaxExempt: true
    },
    createdAt: new Date('2024-02-25'),
    updatedAt: new Date('2024-03-30'),
  },
  {
    id: 'cust_017',
    code: 'CUST017',
    name: 'Southern Oregon Greens',
    contact: 'Michelle Torres',
    email: 'michelle@sogreens.com',
    phone: '541-555-7890',
    address: {
      street: '1414 Southern Blvd',
      city: 'Medford',
      state: 'OR',
      zip: '97504',
      country: 'USA',
    },
    status: 'active',
    creditLimit: 9000.00,
    paymentTerms: 'Net 30',
    notes: 'Interested in concentrates and vapes',
    customFields: {
      licenseNumber: 'OR-DIS-78901',
      preferredDeliveryDay: 'Thursday',
      salesTaxExempt: true
    },
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'cust_018',
    code: 'CUST018',
    name: 'Columbia River Cannabis',
    contact: 'Kevin Johnson',
    email: 'kevin@columbiariver.com',
    phone: '541-555-8901',
    address: {
      street: '1515 Riverside Way',
      city: 'The Dalles',
      state: 'OR',
      zip: '97058',
      country: 'USA',
    },
    status: 'inactive',
    creditLimit: 8500.00,
    paymentTerms: 'Net 30',
    notes: 'Temporarily closed for renovations',
    customFields: {
      licenseNumber: 'OR-DIS-89012',
      preferredDeliveryDay: 'Monday',
      salesTaxExempt: true
    },
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-03-20'),
  },
  {
    id: 'cust_019',
    code: 'CUST019',
    name: 'Crater Lake Dispensary',
    contact: 'Rachel Green',
    email: 'rachel@craterlake.com',
    phone: '541-555-9012',
    address: {
      street: '1616 Lake View Drive',
      city: 'Klamath Falls',
      state: 'OR',
      zip: '97603',
      country: 'USA',
    },
    status: 'pending',
    creditLimit: 6000.00,
    paymentTerms: 'Prepaid',
    notes: 'New location opening soon',
    customFields: {
      licenseNumber: 'OR-DIS-90123-PENDING',
      preferredDeliveryDay: 'Wednesday',
      salesTaxExempt: false
    },
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: 'cust_020',
    code: 'CUST020',
    name: 'Beaver State Hemp',
    contact: 'Brandon Miller',
    email: 'brandon@beaverstatehemp.com',
    phone: '503-555-0123',
    address: {
      street: '1717 State Street',
      city: 'Salem',
      state: 'OR',
      zip: '97301',
      country: 'USA',
    },
    status: 'active',
    creditLimit: 12000.00,
    paymentTerms: 'Net 30',
    notes: 'Wholesale CBD specialist',
    customFields: {
      licenseNumber: 'OR-WHOL-01234',
      preferredDeliveryDay: 'Friday',
      salesTaxExempt: true
    },
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-03-15'),
  },
];

module.exports = {
  customers,
};
