/**
 * Dummy sales data for the ERP system
 * 
 * This file contains sample data for sales/orders to populate
 * the sales management section of the application.
 */

// Create dummy sales/orders
const sales = [
  {
    id: 'sale_001',
    orderNumber: 'ORD-2024-001',
    customerId: 'cust_001',
    customerCode: 'CUST001',
    status: 'delivered',
    items: [
      {
        id: 'item_001_1',
        productId: 'prod_001',
        productSku: 'IND-001',
        productName: 'Premium Indoor Flower - OG Kush',
        quantity: 5,
        unitPrice: 1200.00,
        locationId: 'loc_001',
        subtotal: 6000.00,
        notes: ''
      },
      {
        id: 'item_001_2',
        productId: 'prod_008',
        productSku: 'CON-001',
        productName: 'Live Resin - OG Kush',
        quantity: 50,
        unitPrice: 15.00,
        locationId: 'loc_002',
        subtotal: 750.00,
        notes: ''
      }
    ],
    subtotal: 6750.00,
    taxRate: 0.00,
    taxAmount: 0.00,
    discountType: 'percentage',
    discountValue: 5,
    discountAmount: 337.50,
    total: 6412.50,
    notes: 'Regular monthly order',
    paymentStatus: 'paid',
    paymentMethod: 'bank transfer',
    paymentReference: 'REF123456',
    paymentDate: new Date('2024-01-15'),
    shippingAddress: {
      street: '123 Main Street',
      city: 'Portland',
      state: 'OR',
      zip: '97205',
      country: 'USA',
    },
    shippingMethod: 'company vehicle',
    trackingNumber: '',
    salesRepId: 'user_002',
    commission: 320.63,
    customFields: {
      deliveryInstructions: 'Deliver to back entrance',
      requestedBy: 'Sarah Johnson'
    },
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'sale_002',
    orderNumber: 'ORD-2024-002',
    customerId: 'cust_003',
    customerCode: 'CUST003',
    status: 'delivered',
    items: [
      {
        id: 'item_002_1',
        productId: 'prod_002',
        productSku: 'IND-002',
        productName: 'Premium Indoor Flower - Blue Dream',
        quantity: 8,
        unitPrice: 1150.00,
        locationId: 'loc_001',
        subtotal: 9200.00,
        notes: ''
      },
      {
        id: 'item_002_2',
        productId: 'prod_004',
        productSku: 'OUT-001',
        productName: 'Outdoor Flower - Sour Diesel',
        quantity: 10,
        unitPrice: 800.00,
        locationId: 'loc_001',
        subtotal: 8000.00,
        notes: ''
      }
    ],
    subtotal: 17200.00,
    taxRate: 0.00,
    taxAmount: 0.00,
    discountType: 'fixed',
    discountValue: 1000,
    discountAmount: 1000.00,
    total: 16200.00,
    notes: 'Bulk order discount applied',
    paymentStatus: 'paid',
    paymentMethod: 'check',
    paymentReference: 'CHK4567',
    paymentDate: new Date('2024-01-25'),
    shippingAddress: {
      street: '789 Pine Street',
      city: 'Salem',
      state: 'OR',
      zip: '97301',
      country: 'USA',
    },
    shippingMethod: 'company vehicle',
    trackingNumber: '',
    salesRepId: 'user_003',
    commission: 810.00,
    customFields: {
      deliveryInstructions: 'Call 30 minutes before arrival',
      requestedBy: 'Jessica Martinez'
    },
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: 'sale_003',
    orderNumber: 'ORD-2024-003',
    customerId: 'cust_006',
    customerCode: 'CUST006',
    status: 'delivered',
    items: [
      {
        id: 'item_003_1',
        productId: 'prod_003',
        productSku: 'IND-003',
        productName: 'Premium Indoor Flower - Wedding Cake',
        quantity: 6,
        unitPrice: 1300.00,
        locationId: 'loc_001',
        subtotal: 7800.00,
        notes: ''
      },
      {
        id: 'item_003_2',
        productId: 'prod_010',
        productSku: 'VAP-001',
        productName: 'Vape Cartridge - Sour Diesel',
        quantity: 100,
        unitPrice: 25.00,
        locationId: 'loc_002',
        subtotal: 2500.00,
        notes: ''
      },
      {
        id: 'item_003_3',
        productId: 'prod_011',
        productSku: 'VAP-002',
        productName: 'Vape Cartridge - Wedding Cake',
        quantity: 100,
        unitPrice: 25.00,
        locationId: 'loc_002',
        subtotal: 2500.00,
        notes: ''
      }
    ],
    subtotal: 12800.00,
    taxRate: 0.00,
    taxAmount: 0.00,
    discountType: 'percentage',
    discountValue: 8,
    discountAmount: 1024.00,
    total: 11776.00,
    notes: 'Premium product order',
    paymentStatus: 'paid',
    paymentMethod: 'bank transfer',
    paymentReference: 'REF789012',
    paymentDate: new Date('2024-02-05'),
    shippingAddress: {
      street: '303 Downtown Blvd',
      city: 'Portland',
      state: 'OR',
      zip: '97209',
      country: 'USA',
    },
    shippingMethod: 'company vehicle',
    trackingNumber: '',
    salesRepId: 'user_002',
    commission: 588.80,
    customFields: {
      deliveryInstructions: 'Delivery hours: 9am-5pm',
      requestedBy: 'Robert Taylor'
    },
    createdAt: new Date('2024-01-30'),
    updatedAt: new Date('2024-02-05'),
  },
  {
    id: 'sale_004',
    orderNumber: 'ORD-2024-004',
    customerId: 'cust_010',
    customerCode: 'CUST010',
    status: 'delivered',
    items: [
      {
        id: 'item_004_1',
        productId: 'prod_001',
        productSku: 'IND-001',
        productName: 'Premium Indoor Flower - OG Kush',
        quantity: 10,
        unitPrice: 1200.00,
        locationId: 'loc_001',
        subtotal: 12000.00,
        notes: ''
      },
      {
        id: 'item_004_2',
        productId: 'prod_002',
        productSku: 'IND-002',
        productName: 'Premium Indoor Flower - Blue Dream',
        quantity: 10,
        unitPrice: 1150.00,
        locationId: 'loc_001',
        subtotal: 11500.00,
        notes: ''
      },
      {
        id: 'item_004_3',
        productId: 'prod_003',
        productSku: 'IND-003',
        productName: 'Premium Indoor Flower - Wedding Cake',
        quantity: 8,
        unitPrice: 1300.00,
        locationId: 'loc_001',
        subtotal: 10400.00,
        notes: ''
      }
    ],
    subtotal: 33900.00,
    taxRate: 0.00,
    taxAmount: 0.00,
    discountType: 'percentage',
    discountValue: 10,
    discountAmount: 3390.00,
    total: 30510.00,
    notes: 'Large wholesale order',
    paymentStatus: 'paid',
    paymentMethod: 'bank transfer',
    paymentReference: 'REF345678',
    paymentDate: new Date('2024-02-15'),
    shippingAddress: {
      street: '707 Mountain View Road',
      city: 'Hood River',
      state: 'OR',
      zip: '97031',
      country: 'USA',
    },
    shippingMethod: 'freight',
    trackingNumber: 'FRT12345',
    salesRepId: 'user_003',
    commission: 1525.50,
    customFields: {
      deliveryInstructions: 'Loading dock access required',
      requestedBy: 'Thomas Rodriguez'
    },
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: 'sale_005',
    orderNumber: 'ORD-2024-005',
    customerId: 'cust_008',
    customerCode: 'CUST008',
    status: 'delivered',
    items: [
      {
        id: 'item_005_1',
        productId: 'prod_006',
        productSku: 'LD-001',
        productName: 'Light Dep Flower - Gelato',
        quantity: 5,
        unitPrice: 1000.00,
        locationId: 'loc_001',
        subtotal: 5000.00,
        notes: ''
      },
      {
        id: 'item_005_2',
        productId: 'prod_007',
        productSku: 'LD-002',
        productName: 'Light Dep Flower - Purple Punch',
        quantity: 5,
        unitPrice: 950.00,
        locationId: 'loc_001',
        subtotal: 4750.00,
        notes: ''
      }
    ],
    subtotal: 9750.00,
    taxRate: 0.00,
    taxAmount: 0.00,
    discountType: 'percentage',
    discountValue: 5,
    discountAmount: 487.50,
    total: 9262.50,
    notes: 'First light dep order of the season',
    paymentStatus: 'paid',
    paymentMethod: 'bank transfer',
    paymentReference: 'REF901234',
    paymentDate: new Date('2024-02-25'),
    shippingAddress: {
      street: '505 Forest Avenue',
      city: 'Portland',
      state: 'OR',
      zip: '97221',
      country: 'USA',
    },
    shippingMethod: 'company vehicle',
    trackingNumber: '',
    salesRepId: 'user_002',
    commission: 463.13,
    customFields: {
      deliveryInstructions: 'Deliver before noon',
      requestedBy: 'Daniel Lee'
    },
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-02-25'),
  },
  {
    id: 'sale_006',
    orderNumber: 'ORD-2024-006',
    customerId: 'cust_004',
    customerCode: 'CUST004',
    status: 'delivered',
    items: [
      {
        id: 'item_006_1',
        productId: 'prod_008',
        productSku: 'CON-001',
        productName: 'Live Resin - OG Kush',
        quantity: 100,
        unitPrice: 15.00,
        locationId: 'loc_002',
        subtotal: 1500.00,
        notes: ''
      },
      {
        id: 'item_006_2',
        productId: 'prod_009',
        productSku: 'CON-002',
        productName: 'Shatter - Blue Dream',
        quantity: 100,
        unitPrice: 12.00,
        locationId: 'loc_002',
        subtotal: 1200.00,
        notes: ''
      },
      {
        id: 'item_006_3',
        productId: 'prod_010',
        productSku: 'VAP-001',
        productName: 'Vape Cartridge - Sour Diesel',
        quantity: 50,
        unitPrice: 25.00,
        locationId: 'loc_002',
        subtotal: 1250.00,
        notes: ''
      }
    ],
    subtotal: 3950.00,
    taxRate: 0.00,
    taxAmount: 0.00,
    discountType: 'fixed',
    discountValue: 200,
    discountAmount: 200.00,
    total: 3750.00,
    notes: 'Concentrate and vape order',
    paymentStatus: 'paid',
    paymentMethod: 'credit card',
    paymentReference: 'CC567890',
    paymentDate: new Date('2024-03-05'),
    shippingAddress: {
      street: '101 Summit Road',
      city: 'Bend',
      state: 'OR',
      zip: '97701',
      country: 'USA',
    },
    shippingMethod: 'shipping service',
    trackingNumber: 'TRK123456',
    salesRepId: 'user_004',
    commission: 187.50,
    customFields: {
      deliveryInstructions: 'Signature required',
      requestedBy: 'David Wilson'
    },
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-05'),
  },
  {
    id: 'sale_007',
    orderNumber: 'ORD-2024-007',
    customerId: 'cust_016',
    customerCode: 'CUST016',
    status: 'delivered',
    items: [
      {
        id: 'item_007_1',
        productId: 'prod_001',
        productSku: 'IND-001',
        productName: 'Premium Indoor Flower - OG Kush',
        quantity: 3,
        unitPrice: 1200.00,
        locationId: 'loc_001',
        subtotal: 3600.00,
        notes: ''
      },
      {
        id: 'item_007_2',
        productId: 'prod_003',
        productSku: 'IND-003',
        productName: 'Premium Indoor Flower - Wedding Cake',
        quantity: 3,
        unitPrice: 1300.00,
        locationId: 'loc_001',
        subtotal: 3900.00,
        notes: ''
      },
      {
        id: 'item_007_3',
        productId: 'prod_008',
        productSku: 'CON-001',
        productName: 'Live Resin - OG Kush',
        quantity: 50,
        unitPrice: 15.00,
        locationId: 'loc_002',
        subtotal: 750.00,
        notes: ''
      }
    ],
    subtotal: 8250.00,
    taxRate: 0.00,
    taxAmount: 0.00,
    discountType: 'percentage',
    discountValue: 5,
    discountAmount: 412.50,
    total: 7837.50,
    notes: 'Mixed product order',
    paymentStatus: 'paid',
    paymentMethod: 'bank transfer',
    paymentReference: 'REF123789',
    paymentDate: new Date('2024-03-15'),
    shippingAddress: {
      street: '1313 Rose Avenue',
      city: 'Portland',
      state: 'OR',
      zip: '97232',
      country: 'USA',
    },
    shippingMethod: 'company vehicle',
    trackingNumber: '',
    salesRepId: 'user_002',
    commission: 391.88,
    customFields: {
      deliveryInstructions: 'Call on arrival',
      requestedBy: 'Andrew Scott'
    },
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: 'sale_008',
    orderNumber: 'ORD-2024-008',
    customerId: 'cust_020',
    customerCode: 'CUST020',
    status: 'delivered',
    items: [
      {
        id: 'item_008_1',
        productId: 'prod_012',
        productSku: 'OTH-001',
        productName: 'CBD Tincture - 1000mg',
        quantity: 50,
        unitPrice: 50.00,
        locationId: 'loc_002',
        subtotal: 2500.00,
        notes: ''
      },
      {
        id: 'item_008_2',
        productId: 'prod_013',
        productSku: 'OTH-002',
        productName: 'Hemp Pre-Rolls - 5 Pack',
        quantity: 100,
        unitPrice: 20.00,
        locationId: 'loc_002',
        subtotal: 2000.00,
        notes: ''
      }
    ],
    subtotal: 4500.00,
    taxRate: 0.00,
    taxAmount: 0.00,
    discountType: 'percentage',
    discountValue: 10,
    discountAmount: 450.00,
    total: 4050.00,
    notes: 'CBD product wholesale order',
    paymentStatus: 'paid',
    paymentMethod: 'bank transfer',
    paymentReference: 'REF456123',
    paymentDate: new Date('2024-03-25'),
    shippingAddress: {
      street: '1717 State Street',
      city: 'Salem',
      state: 'OR',
      zip: '97301',
      country: 'USA',
    },
    shippingMethod: 'shipping service',
    trackingNumber: 'TRK789012',
    salesRepId: 'user_003',
    commission: 202.50,
    customFields: {
      deliveryInstructions: 'Business hours delivery only',
      requestedBy: 'Brandon Miller'
    },
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-03-25'),
  },
  {
    id: 'sale_009',
    orderNumber: 'ORD-2024-009',
    customerId: 'cust_002',
    customerCode: 'CUST002',
    status: 'shipped',
    items: [
      {
        id: 'item_009_1',
        productId: 'prod_002',
        productSku: 'IND-002',
        productName: 'Premium Indoor Flower - Blue Dream',
        quantity: 4,
        unitPrice: 1150.00,
        locationId: 'loc_001',
        subtotal: 4600.00,
        notes: ''
      },
      {
        id: 'item_009_2',
        productId: 'prod_006',
        productSku: 'LD-001',
        productName: 'Light Dep Flower - Gelato',
        quantity: 3,
        unitPrice: 1000.00,
        locationId: 'loc_001',
        subtotal: 3000.00,
        notes: ''
      }
    ],
    subtotal: 7600.00,
    taxRate: 0.00,
    taxAmount: 0.00,
    discountType: 'percentage',
    discountValue: 5,
    discountAmount: 380.00,
    total: 7220.00,
    notes: 'Regular monthly order',
    paymentStatus: 'paid',
    paymentMethod: 'bank transfer',
    paymentReference: 'REF789456',
    paymentDate: new Date('2024-03-30'),
    shippingAddress: {
      street: '456 Oak Avenue',
      city: 'Eugene',
      state: 'OR',
      zip: '97401',
      country: 'USA',
    },
    shippingMethod: 'shipping service',
    trackingNumber: 'TRK345678',
    salesRepId: 'user_004',
    commission: 361.00,
    customFields: {
      deliveryInstructions: 'Deliver before 3pm',
      requestedBy: 'Michael Chen'
    },
    createdAt: new Date('2024-03-28'),
    updatedAt: new Date('2024-03-30'),
  },
  {
    id: 'sale_010',
    orderNumber: 'ORD-2024-010',
    customerId: 'cust_005',
    customerCode: 'CUST005',
    status: 'processing',
    items: [
      {
        id: 'item_010_1',
        productId: 'prod_004',
        productSku: 'OUT-001',
        productName: 'Outdoor Flower - Sour Diesel',
        quantity: 5,
        unitPrice: 800.00,
        locationId: 'loc_001',
        subtotal: 4000.00,
        notes: ''
      },
      {
        id: 'item_010_2',
        productId: 'prod_005',
        productSku: 'OUT-002',
        productName: 'Outdoor Flower - Jack Herer',
        quantity: 5,
        unitPrice: 850.00,
        locationId: 'loc_001',
        subtotal: 4250.00,
        notes: ''
      },
      {
        id: 'item_010_3',
        productId: 'prod_010',
        productSku: 'VAP-001',
        productName: 'Vape Cartridge - Sour Diesel',
        quantity: 25,
        unitPrice: 25.00,
        locationId: 'loc_002',
        subtotal: 625.00,
        notes: ''
      }
    ],
    subtotal: 8875.00,
    taxRate: 0.00,
    taxAmount: 0.00,
    discountType: 'fixed',
    discountValue: 500,
    discountAmount: 500.00,
    total: 8375.00,
    notes: 'Seasonal order for summer stock',
    paymentStatus: 'unpaid',
    paymentMethod: '',
    paymentReference: '',
    paymentDate: null,
    shippingAddress: {
      street: '202 Beach Drive',
      city: 'Newport',
      state: 'OR',
      zip: '97365',
      country: 'USA',
    },
    shippingMethod: 'shipping service',
    trackingNumber: '',
    salesRepId: 'user_003',
    commission: 418.75,
    customFields: {
      deliveryInstructions: 'Notify before shipping',
      requestedBy: 'Emily Brown'
    },
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-04-01'),
  },
  {
    id: 'sale_011',
    orderNumber: 'ORD-2024-011',
    customerId: 'cust_009',
    customerCode: 'CUST009',
    status: 'pending',
    items: [
      {
        id: 'item_011_1',
        productId: 'prod_012',
        productSku: 'OTH-001',
        productName: 'CBD Tincture - 1000mg',
        quantity: 20,
        unitPrice: 50.00,
        locationId: 'loc_002',
        subtotal: 1000.00,
        notes: ''
      },
      {
        id: 'item_011_2',
        productId: 'prod_013',
        productSku: 'OTH-002',
        productName: 'Hemp Pre-Rolls - 5 Pack',
        quantity: 30,
        unitPrice: 20.00,
        locationId: 'loc_002',
        subtotal: 600.00,
        notes: ''
      }
    ],
    subtotal: 1600.00,
    taxRate: 0.00,
    taxAmount: 0.00,
    discountType: 'percentage',
    discountValue: 0,
    discountAmount: 0.00,
    total: 1600.00,
    notes: 'CBD products for medicinal focus',
    paymentStatus: 'unpaid',
    paymentMethod: '',
    paymentReference: '',
    paymentDate: null,
    shippingAddress: {
      street: '606 Wellness Way',
      city: 'Ashland',
      state: 'OR',
      zip: '97520',
      country: 'USA',
    },
    shippingMethod: 'shipping service',
    trackingNumber: '',
    salesRepId: 'user_004',
    commission: 80.00,
    customFields: {
      deliveryInstructions: 'Discreet packaging requested',
      requestedBy: 'Sophia Patel'
    },
    createdAt: new Date('2024-04-02'),
    updatedAt: new Date('2024-04-02'),
  },
  {
    id: 'sale_012',
    orderNumber: 'ORD-2024-012',
    customerId: 'cust_001',
    customerCode: 'CUST001',
    status: 'pending',
    items: [
      {
        id: 'item_012_1',
        productId: 'prod_001',
        productSku: 'IND-001',
        productName: 'Premium Indoor Flower - OG Kush',
        quantity: 5,
        unitPrice: 1200.00,
        locationId: 'loc_001',
        subtotal: 6000.00,
        notes: ''
      },
      {
        id: 'item_012_2',
        productId: 'prod_003',
        productSku: 'IND-003',
        productName: 'Premium Indoor Flower - Wedding Cake',
        quantity: 3,
        unitPrice: 1300.00,
        locationId: 'loc_001',
        subtotal: 3900.00,
        notes: ''
      },
      {
        id: 'item_012_3',
        productId: 'prod_008',
        productSku: 'CON-001',
        productName: 'Live Resin - OG Kush',
        quantity: 50,
        unitPrice: 15.00,
        locationId: 'loc_002',
        subtotal: 750.00,
        notes: ''
      }
    ],
    subtotal: 10650.00,
    taxRate: 0.00,
    taxAmount: 0.00,
    discountType: 'percentage',
    discountValue: 5,
    discountAmount: 532.50,
    total: 10117.50,
    notes: 'Monthly restock order',
    paymentStatus: 'unpaid',
    paymentMethod: '',
    paymentReference: '',
    paymentDate: null,
    shippingAddress: {
      street: '123 Main Street',
      city: 'Portland',
      state: 'OR',
      zip: '97205',
      country: 'USA',
    },
    shippingMethod: 'company vehicle',
    trackingNumber: '',
    salesRepId: 'user_002',
    commission: 505.88,
    customFields: {
      deliveryInstructions: 'Deliver to back entrance',
      requestedBy: 'Sarah Johnson'
    },
    createdAt: new Date('2024-04-03'),
    updatedAt: new Date('2024-04-03'),
  },
];

module.exports = {
  sales,
};
