name: ERP System CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # Weekly backup on Sundays at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: npm run lint || true
    
    - name: Run tests
      run: npm test || true
    
    - name: Build project
      run: npm run build
    
    - name: Create backup
      run: |
        zip -r backup-$(date +"%Y%m%d%H%M%S").zip . -x "node_modules/*" ".git/*"
    
    - name: Upload backup as artifact
      uses: actions/upload-artifact@v3
      with:
        name: backup
        path: backup-*.zip
        retention-days: 30
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Install Vercel CLI
      run: npm install -g vercel

    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      run: |
        # Deploy to Vercel using the CLI with production flag
        vercel deploy --prod --token=$VERCEL_TOKEN
    
    - name: Update PROJECT_STATUS.md
      run: |
        # Update the last updated date in the status file
        sed -i "s/- \*\*Last Updated\*\*: .*/- \*\*Last Updated\*\*: $(date +'%B %d, %Y')/" PROJECT_STATUS.md
        
        # Commit the updated status file
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add PROJECT_STATUS.md
        git commit -m "Update PROJECT_STATUS.md with latest deployment date" || echo "No changes to commit"
        git push
